In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.svm import SVC

In [3]:
df = pd.read_csv("train.csv")
df.head()

,labels,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
0,0,-2.033875,0.978446,-0.142131,-0.177117,-1.470684,1.669562,-0.196530,-0.125239,-0.452284,...,-1.111266,0.716084,0.060039,0.301279,-1.174846,-1.076498,-0.069452,-0.604012,-2.179176,0.558003
1,1,-0.348835,0.294815,-0.557577,-2.020773,-1.234715,1.633930,-1.680658,-0.358146,0.166122,...,0.735240,0.829781,1.521941,1.347946,0.754505,1.330642,-0.754453,0.582956,0.252671,1.495870
2,1,0.113248,-0.607726,-0.947791,0.830851,0.998291,0.498321,-1.493958,0.789572,-1.311018,...,0.104698,0.616189,-1.035953,2.111387,-0.984415,1.148076,-1.433554,0.243372,0.170083,1.274795
3,0,1.223321,-0.479048,-1.925789,1.680377,0.021840,-1.453307,0.605559,-0.019024,1.065448,...,0.360237,-1.957863,-0.123384,1.505329,0.660290,-1.769443,-0.547756,-0.568122,0.244645,0.982116
4,0,0.160109,0.422684,-0.308029,0.227744,0.432854,0.608348,0.193832,1.035091,-0.538868,...,0.416629,1.441766,0.212572,-0.994721,1.143999,-2.166923,-1.199248,-1.028636,0.752791,0.317169

In [4]:
model = SVC(kernel = 'poly', degree = 2)

In [5]:
X = df.drop('labels',axis = 1)
Y = df['labels']

In [6]:
X.shape

(5250, 1200)

In [7]:
df.describe()

,labels,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
count,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,...,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000,5250.000000
mean,0.266667,0.385453,0.086769,0.317084,0.400414,0.093063,0.173532,-0.174072,-0.074659,-0.135957,...,0.417874,-0.405061,0.091497,-0.276132,-0.133123,-0.156475,-0.096026,0.372260,-0.222551,0.006532
std,0.442259,0.929075,0.898979,0.969380,0.954504,0.968625,0.895351,1.001566,0.906168,0.972163,...,0.941354,1.054231,0.958970,0.989820,1.042036,1.019384,0.913732,0.944429,0.973640,0.897006
min,0.000000,-3.462941,-3.605773,-4.078232,-3.344323,-3.613712,-3.319666,-3.627701,-3.528635,-4.503662,...,-3.684054,-3.385650,-3.162629,-3.022903,-3.698249,-4.791005,-3.356509,-3.933762,-4.174752,-3.624981
25%,0.000000,-0.286854,-0.470281,-0.379984,-0.290078,-0.644337,-0.392807,-0.980593,-0.677763,-0.914803,...,-0.254776,-1.265848,-0.594289,-1.054700,-1.009256,-0.833164,-0.684567,-0.301254,-1.010557,-0.564394
50%,0.000000,0.598422,0.071867,0.518698,0.653512,0.141549,0.237502,-0.180645,-0.159631,-0.108885,...,0.648944,-0.489479,0.192821,-0.301887,-0.139792,-0.197277,-0.156927,0.612440,-0.241763,-0.008017
75%,1.000000,1.108212,0.609769,1.085552,1.135854,0.950304,0.747622,0.621790,0.450741,0.627055,...,1.131876,0.366639,0.779280,0.409370,0.740059,0.493094,0.434146,1.109200,0.508097,0.552090
max,1.000000,3.439295,3.581171,3.991985,3.900672,3.488667,3.193113,3.062756,3.877255,3.017000,...,4.077517,3.550058,3.790435,3.907684,3.777545,3.269490,3.526907,3.542401,3.642856,3.718869

In [8]:
df.isnull().sum()

labels    0
f_0       0
f_1       0
f_2       0
f_3       0
         ..
f_1195    0
f_1196    0
f_1197    0
f_1198    0
f_1199    0
Length: 1201, dtype: int64

In [9]:
df.isnull()

,labels,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5246,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5247,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5249,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
from sklearn.model_selection import train_test_split
train,test,Y_train,Y_tests = train_test_split(X,Y, test_size=0.2, random_state = 20113046)

In [12]:
model.fit(train,Y_train)

SVC(degree=2, kernel='poly')

In [13]:
pred = model.predict(train)

In [ ]:
confusion_matrix(pred,Y_train)

array([[3090,    0],
       [   0, 1110]], dtype=int64)

In [14]:
import scipy.stats

In [15]:
print("R2 score : ",model.score(train,Y_train))

R2 score :  1.0

In [16]:
import seaborn as sns
from matplotlib import pyplot as plt
from scipy.stats import pearsonr
from sklearn.metrics import confusion_matrix

In [17]:
from sklearn.metrics import classification_report

In [18]:
print('Classification Report for svm with polynomial kernel :\n',classification_report(Y_train,pred))

Classification Report for svm with polynomial kernel :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3090
           1       1.00      1.00      1.00      1110

    accuracy                           1.00      4200
   macro avg       1.00      1.00      1.00      4200
weighted avg       1.00      1.00      1.00      4200

In [19]:
pred_test = model.predict(test)

In [20]:
print("R2 score : ",model.score(test,Y_tests))

R2 score :  0.8495238095238096

In [21]:
print('Classification Report for svm with polynomial kernel on test data:\n',classification_report(Y_tests,pred_test))

Classification Report for svm with polynomial kernel on test data:
               precision    recall  f1-score   support

           0       0.83      1.00      0.91       760
           1       1.00      0.46      0.63       290

    accuracy                           0.85      1050
   macro avg       0.91      0.73      0.77      1050
weighted avg       0.88      0.85      0.83      1050

In [22]:
df2 = pd.read_csv("test.csv")
df2.head()

,id,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,...,f_1190,f_1191,f_1192,f_1193,f_1194,f_1195,f_1196,f_1197,f_1198,f_1199
0,1,-3.388242,0.868285,-0.427619,-0.678964,-1.625735,0.262761,1.243040,1.537751,-0.352028,...,-0.776403,-0.662884,-0.257091,-1.168413,0.223260,-0.482520,-0.085453,-0.382265,-0.539349,-1.682404
1,2,-0.496920,0.952381,0.989040,0.451422,0.513516,-0.099658,-1.124326,0.729430,-0.216224,...,0.379635,-1.760084,1.125450,-0.328047,-0.880305,-1.257607,0.964312,2.021104,0.655021,-0.423029
2,3,1.128369,-0.537951,2.544358,1.165254,-1.904994,0.776961,-0.495768,0.060111,-1.418468,...,1.165254,-1.373589,-0.483701,-0.964782,-0.869555,0.066040,-0.444567,-0.531935,-0.878660,1.099488
3,4,0.051253,1.746814,0.681177,1.844524,-0.327977,1.226839,-0.085519,0.379008,-1.003667,...,-0.442288,-2.794472,-0.763468,-0.789832,-0.113209,-2.703150,-2.058728,1.070627,-0.458045,-0.435825
4,5,1.423209,-0.983594,-1.694170,1.197507,1.044211,0.518777,-0.298612,-0.365174,0.738447,...,-2.624450,-3.200223,0.711422,-0.190394,0.337224,-1.656639,0.707360,-0.562290,1.471181,-0.192000

In [30]:
X_test = df2.drop("id",axis=1)
X_test.shape

(2250, 1200)

/*Y_ans stores values of the labels of the test dataset provided by the competition*/

In [32]:
Y_ans = model.predict(X_test)

In [35]:
Y_ans.shape

(2250,)

In [39]:
Y_ans[2249]

1

In [57]:
rows = np.empty((2250,2))
rows.shape

(2250, 2)

In [58]:
rows.dtype

dtype('float64')

In [59]:
new_rows = rows.astype('i')
new_rows.dtype

dtype('int32')

In [60]:
new_rows[1][0],new_rows[1][1]

(0, 0)

In [61]:
for i in range(2250):
    new_rows[i][0]=i+1
    new_rows[i][1]=Y_ans[i]

In [62]:
new_rows[3][0],new_rows[3][1],new_rows[2249][1]

(4, 0, 1)

In [63]:
# writing to CSV


import csv
	
# field names
fields = ['id', 'labels']
	
rows = new_rows
	
# name of csv file
filename = "solution.csv"
	
# writing to csv file 
with open(filename, 'w', newline = '') as csvfile: 
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
        
    # writing the fields 
    csvwriter.writerow(fields) 
        
    # writing the data rows 
    csvwriter.writerows(rows)

/*Solution.csv file is used for submission on bitgrit*/

In [64]:
# Y_ans[1300], Y_ans[1299]

(1, 0)

In [66]:
df4 = pd.read_csv("solution.csv")
df4.head()

   id  labels
0   1       0
1   2       0
2   3       0
3   4       0
4   5       0